
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DockerHost` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DockerHost
 * 
 */
export type DockerHostModel = runtime.Types.Result.DefaultSelection<Prisma.$DockerHostPayload>

export type AggregateDockerHost = {
  _count: DockerHostCountAggregateOutputType | null
  _avg: DockerHostAvgAggregateOutputType | null
  _sum: DockerHostSumAggregateOutputType | null
  _min: DockerHostMinAggregateOutputType | null
  _max: DockerHostMaxAggregateOutputType | null
}

export type DockerHostAvgAggregateOutputType = {
  id: number | null
  userId: number | null
}

export type DockerHostSumAggregateOutputType = {
  id: number | null
  userId: number | null
}

export type DockerHostMinAggregateOutputType = {
  id: number | null
  uuid: string | null
  name: string | null
  url: string | null
  authKey: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: number | null
}

export type DockerHostMaxAggregateOutputType = {
  id: number | null
  uuid: string | null
  name: string | null
  url: string | null
  authKey: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: number | null
}

export type DockerHostCountAggregateOutputType = {
  id: number
  uuid: number
  name: number
  url: number
  authKey: number
  isActive: number
  createdAt: number
  updatedAt: number
  userId: number
  _all: number
}


export type DockerHostAvgAggregateInputType = {
  id?: true
  userId?: true
}

export type DockerHostSumAggregateInputType = {
  id?: true
  userId?: true
}

export type DockerHostMinAggregateInputType = {
  id?: true
  uuid?: true
  name?: true
  url?: true
  authKey?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
}

export type DockerHostMaxAggregateInputType = {
  id?: true
  uuid?: true
  name?: true
  url?: true
  authKey?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
}

export type DockerHostCountAggregateInputType = {
  id?: true
  uuid?: true
  name?: true
  url?: true
  authKey?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  _all?: true
}

export type DockerHostAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DockerHost to aggregate.
   */
  where?: Prisma.DockerHostWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DockerHosts to fetch.
   */
  orderBy?: Prisma.DockerHostOrderByWithRelationInput | Prisma.DockerHostOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DockerHostWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DockerHosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DockerHosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DockerHosts
  **/
  _count?: true | DockerHostCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DockerHostAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DockerHostSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DockerHostMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DockerHostMaxAggregateInputType
}

export type GetDockerHostAggregateType<T extends DockerHostAggregateArgs> = {
      [P in keyof T & keyof AggregateDockerHost]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDockerHost[P]>
    : Prisma.GetScalarType<T[P], AggregateDockerHost[P]>
}




export type DockerHostGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DockerHostWhereInput
  orderBy?: Prisma.DockerHostOrderByWithAggregationInput | Prisma.DockerHostOrderByWithAggregationInput[]
  by: Prisma.DockerHostScalarFieldEnum[] | Prisma.DockerHostScalarFieldEnum
  having?: Prisma.DockerHostScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DockerHostCountAggregateInputType | true
  _avg?: DockerHostAvgAggregateInputType
  _sum?: DockerHostSumAggregateInputType
  _min?: DockerHostMinAggregateInputType
  _max?: DockerHostMaxAggregateInputType
}

export type DockerHostGroupByOutputType = {
  id: number
  uuid: string
  name: string
  url: string
  authKey: string
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  userId: number
  _count: DockerHostCountAggregateOutputType | null
  _avg: DockerHostAvgAggregateOutputType | null
  _sum: DockerHostSumAggregateOutputType | null
  _min: DockerHostMinAggregateOutputType | null
  _max: DockerHostMaxAggregateOutputType | null
}

type GetDockerHostGroupByPayload<T extends DockerHostGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DockerHostGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DockerHostGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DockerHostGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DockerHostGroupByOutputType[P]>
      }
    >
  >



export type DockerHostWhereInput = {
  AND?: Prisma.DockerHostWhereInput | Prisma.DockerHostWhereInput[]
  OR?: Prisma.DockerHostWhereInput[]
  NOT?: Prisma.DockerHostWhereInput | Prisma.DockerHostWhereInput[]
  id?: Prisma.IntFilter<"DockerHost"> | number
  uuid?: Prisma.StringFilter<"DockerHost"> | string
  name?: Prisma.StringFilter<"DockerHost"> | string
  url?: Prisma.StringFilter<"DockerHost"> | string
  authKey?: Prisma.StringFilter<"DockerHost"> | string
  isActive?: Prisma.BoolFilter<"DockerHost"> | boolean
  createdAt?: Prisma.DateTimeFilter<"DockerHost"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DockerHost"> | Date | string
  userId?: Prisma.IntFilter<"DockerHost"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type DockerHostOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  uuid?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  authKey?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type DockerHostWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  uuid?: string
  AND?: Prisma.DockerHostWhereInput | Prisma.DockerHostWhereInput[]
  OR?: Prisma.DockerHostWhereInput[]
  NOT?: Prisma.DockerHostWhereInput | Prisma.DockerHostWhereInput[]
  name?: Prisma.StringFilter<"DockerHost"> | string
  url?: Prisma.StringFilter<"DockerHost"> | string
  authKey?: Prisma.StringFilter<"DockerHost"> | string
  isActive?: Prisma.BoolFilter<"DockerHost"> | boolean
  createdAt?: Prisma.DateTimeFilter<"DockerHost"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DockerHost"> | Date | string
  userId?: Prisma.IntFilter<"DockerHost"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "uuid">

export type DockerHostOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  uuid?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  authKey?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.DockerHostCountOrderByAggregateInput
  _avg?: Prisma.DockerHostAvgOrderByAggregateInput
  _max?: Prisma.DockerHostMaxOrderByAggregateInput
  _min?: Prisma.DockerHostMinOrderByAggregateInput
  _sum?: Prisma.DockerHostSumOrderByAggregateInput
}

export type DockerHostScalarWhereWithAggregatesInput = {
  AND?: Prisma.DockerHostScalarWhereWithAggregatesInput | Prisma.DockerHostScalarWhereWithAggregatesInput[]
  OR?: Prisma.DockerHostScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DockerHostScalarWhereWithAggregatesInput | Prisma.DockerHostScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"DockerHost"> | number
  uuid?: Prisma.StringWithAggregatesFilter<"DockerHost"> | string
  name?: Prisma.StringWithAggregatesFilter<"DockerHost"> | string
  url?: Prisma.StringWithAggregatesFilter<"DockerHost"> | string
  authKey?: Prisma.StringWithAggregatesFilter<"DockerHost"> | string
  isActive?: Prisma.BoolWithAggregatesFilter<"DockerHost"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DockerHost"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DockerHost"> | Date | string
  userId?: Prisma.IntWithAggregatesFilter<"DockerHost"> | number
}

export type DockerHostCreateInput = {
  uuid?: string
  name: string
  url: string
  authKey: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutDockerHostsInput
}

export type DockerHostUncheckedCreateInput = {
  id?: number
  uuid?: string
  name: string
  url: string
  authKey: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: number
}

export type DockerHostUpdateInput = {
  uuid?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  authKey?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutDockerHostsNestedInput
}

export type DockerHostUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  uuid?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  authKey?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type DockerHostCreateManyInput = {
  id?: number
  uuid?: string
  name: string
  url: string
  authKey: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: number
}

export type DockerHostUpdateManyMutationInput = {
  uuid?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  authKey?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DockerHostUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  uuid?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  authKey?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type DockerHostListRelationFilter = {
  every?: Prisma.DockerHostWhereInput
  some?: Prisma.DockerHostWhereInput
  none?: Prisma.DockerHostWhereInput
}

export type DockerHostOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DockerHostCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  uuid?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  authKey?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type DockerHostAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type DockerHostMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  uuid?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  authKey?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type DockerHostMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  uuid?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  authKey?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type DockerHostSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type DockerHostCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.DockerHostCreateWithoutUserInput, Prisma.DockerHostUncheckedCreateWithoutUserInput> | Prisma.DockerHostCreateWithoutUserInput[] | Prisma.DockerHostUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DockerHostCreateOrConnectWithoutUserInput | Prisma.DockerHostCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.DockerHostCreateManyUserInputEnvelope
  connect?: Prisma.DockerHostWhereUniqueInput | Prisma.DockerHostWhereUniqueInput[]
}

export type DockerHostUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.DockerHostCreateWithoutUserInput, Prisma.DockerHostUncheckedCreateWithoutUserInput> | Prisma.DockerHostCreateWithoutUserInput[] | Prisma.DockerHostUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DockerHostCreateOrConnectWithoutUserInput | Prisma.DockerHostCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.DockerHostCreateManyUserInputEnvelope
  connect?: Prisma.DockerHostWhereUniqueInput | Prisma.DockerHostWhereUniqueInput[]
}

export type DockerHostUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.DockerHostCreateWithoutUserInput, Prisma.DockerHostUncheckedCreateWithoutUserInput> | Prisma.DockerHostCreateWithoutUserInput[] | Prisma.DockerHostUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DockerHostCreateOrConnectWithoutUserInput | Prisma.DockerHostCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.DockerHostUpsertWithWhereUniqueWithoutUserInput | Prisma.DockerHostUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.DockerHostCreateManyUserInputEnvelope
  set?: Prisma.DockerHostWhereUniqueInput | Prisma.DockerHostWhereUniqueInput[]
  disconnect?: Prisma.DockerHostWhereUniqueInput | Prisma.DockerHostWhereUniqueInput[]
  delete?: Prisma.DockerHostWhereUniqueInput | Prisma.DockerHostWhereUniqueInput[]
  connect?: Prisma.DockerHostWhereUniqueInput | Prisma.DockerHostWhereUniqueInput[]
  update?: Prisma.DockerHostUpdateWithWhereUniqueWithoutUserInput | Prisma.DockerHostUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.DockerHostUpdateManyWithWhereWithoutUserInput | Prisma.DockerHostUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.DockerHostScalarWhereInput | Prisma.DockerHostScalarWhereInput[]
}

export type DockerHostUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.DockerHostCreateWithoutUserInput, Prisma.DockerHostUncheckedCreateWithoutUserInput> | Prisma.DockerHostCreateWithoutUserInput[] | Prisma.DockerHostUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DockerHostCreateOrConnectWithoutUserInput | Prisma.DockerHostCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.DockerHostUpsertWithWhereUniqueWithoutUserInput | Prisma.DockerHostUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.DockerHostCreateManyUserInputEnvelope
  set?: Prisma.DockerHostWhereUniqueInput | Prisma.DockerHostWhereUniqueInput[]
  disconnect?: Prisma.DockerHostWhereUniqueInput | Prisma.DockerHostWhereUniqueInput[]
  delete?: Prisma.DockerHostWhereUniqueInput | Prisma.DockerHostWhereUniqueInput[]
  connect?: Prisma.DockerHostWhereUniqueInput | Prisma.DockerHostWhereUniqueInput[]
  update?: Prisma.DockerHostUpdateWithWhereUniqueWithoutUserInput | Prisma.DockerHostUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.DockerHostUpdateManyWithWhereWithoutUserInput | Prisma.DockerHostUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.DockerHostScalarWhereInput | Prisma.DockerHostScalarWhereInput[]
}

export type DockerHostCreateWithoutUserInput = {
  uuid?: string
  name: string
  url: string
  authKey: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DockerHostUncheckedCreateWithoutUserInput = {
  id?: number
  uuid?: string
  name: string
  url: string
  authKey: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DockerHostCreateOrConnectWithoutUserInput = {
  where: Prisma.DockerHostWhereUniqueInput
  create: Prisma.XOR<Prisma.DockerHostCreateWithoutUserInput, Prisma.DockerHostUncheckedCreateWithoutUserInput>
}

export type DockerHostCreateManyUserInputEnvelope = {
  data: Prisma.DockerHostCreateManyUserInput | Prisma.DockerHostCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type DockerHostUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.DockerHostWhereUniqueInput
  update: Prisma.XOR<Prisma.DockerHostUpdateWithoutUserInput, Prisma.DockerHostUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.DockerHostCreateWithoutUserInput, Prisma.DockerHostUncheckedCreateWithoutUserInput>
}

export type DockerHostUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.DockerHostWhereUniqueInput
  data: Prisma.XOR<Prisma.DockerHostUpdateWithoutUserInput, Prisma.DockerHostUncheckedUpdateWithoutUserInput>
}

export type DockerHostUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.DockerHostScalarWhereInput
  data: Prisma.XOR<Prisma.DockerHostUpdateManyMutationInput, Prisma.DockerHostUncheckedUpdateManyWithoutUserInput>
}

export type DockerHostScalarWhereInput = {
  AND?: Prisma.DockerHostScalarWhereInput | Prisma.DockerHostScalarWhereInput[]
  OR?: Prisma.DockerHostScalarWhereInput[]
  NOT?: Prisma.DockerHostScalarWhereInput | Prisma.DockerHostScalarWhereInput[]
  id?: Prisma.IntFilter<"DockerHost"> | number
  uuid?: Prisma.StringFilter<"DockerHost"> | string
  name?: Prisma.StringFilter<"DockerHost"> | string
  url?: Prisma.StringFilter<"DockerHost"> | string
  authKey?: Prisma.StringFilter<"DockerHost"> | string
  isActive?: Prisma.BoolFilter<"DockerHost"> | boolean
  createdAt?: Prisma.DateTimeFilter<"DockerHost"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DockerHost"> | Date | string
  userId?: Prisma.IntFilter<"DockerHost"> | number
}

export type DockerHostCreateManyUserInput = {
  id?: number
  uuid?: string
  name: string
  url: string
  authKey: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DockerHostUpdateWithoutUserInput = {
  uuid?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  authKey?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DockerHostUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  uuid?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  authKey?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DockerHostUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  uuid?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  authKey?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type DockerHostSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  uuid?: boolean
  name?: boolean
  url?: boolean
  authKey?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dockerHost"]>

export type DockerHostSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  uuid?: boolean
  name?: boolean
  url?: boolean
  authKey?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dockerHost"]>

export type DockerHostSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  uuid?: boolean
  name?: boolean
  url?: boolean
  authKey?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dockerHost"]>

export type DockerHostSelectScalar = {
  id?: boolean
  uuid?: boolean
  name?: boolean
  url?: boolean
  authKey?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
}

export type DockerHostOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "uuid" | "name" | "url" | "authKey" | "isActive" | "createdAt" | "updatedAt" | "userId", ExtArgs["result"]["dockerHost"]>
export type DockerHostInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type DockerHostIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type DockerHostIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $DockerHostPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DockerHost"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    uuid: string
    name: string
    url: string
    authKey: string
    isActive: boolean
    createdAt: Date
    updatedAt: Date
    userId: number
  }, ExtArgs["result"]["dockerHost"]>
  composites: {}
}

export type DockerHostGetPayload<S extends boolean | null | undefined | DockerHostDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DockerHostPayload, S>

export type DockerHostCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DockerHostFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DockerHostCountAggregateInputType | true
  }

export interface DockerHostDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DockerHost'], meta: { name: 'DockerHost' } }
  /**
   * Find zero or one DockerHost that matches the filter.
   * @param {DockerHostFindUniqueArgs} args - Arguments to find a DockerHost
   * @example
   * // Get one DockerHost
   * const dockerHost = await prisma.dockerHost.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DockerHostFindUniqueArgs>(args: Prisma.SelectSubset<T, DockerHostFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DockerHostClient<runtime.Types.Result.GetResult<Prisma.$DockerHostPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DockerHost that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DockerHostFindUniqueOrThrowArgs} args - Arguments to find a DockerHost
   * @example
   * // Get one DockerHost
   * const dockerHost = await prisma.dockerHost.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DockerHostFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DockerHostFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DockerHostClient<runtime.Types.Result.GetResult<Prisma.$DockerHostPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DockerHost that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DockerHostFindFirstArgs} args - Arguments to find a DockerHost
   * @example
   * // Get one DockerHost
   * const dockerHost = await prisma.dockerHost.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DockerHostFindFirstArgs>(args?: Prisma.SelectSubset<T, DockerHostFindFirstArgs<ExtArgs>>): Prisma.Prisma__DockerHostClient<runtime.Types.Result.GetResult<Prisma.$DockerHostPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DockerHost that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DockerHostFindFirstOrThrowArgs} args - Arguments to find a DockerHost
   * @example
   * // Get one DockerHost
   * const dockerHost = await prisma.dockerHost.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DockerHostFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DockerHostFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DockerHostClient<runtime.Types.Result.GetResult<Prisma.$DockerHostPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DockerHosts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DockerHostFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DockerHosts
   * const dockerHosts = await prisma.dockerHost.findMany()
   * 
   * // Get first 10 DockerHosts
   * const dockerHosts = await prisma.dockerHost.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dockerHostWithIdOnly = await prisma.dockerHost.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DockerHostFindManyArgs>(args?: Prisma.SelectSubset<T, DockerHostFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DockerHostPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DockerHost.
   * @param {DockerHostCreateArgs} args - Arguments to create a DockerHost.
   * @example
   * // Create one DockerHost
   * const DockerHost = await prisma.dockerHost.create({
   *   data: {
   *     // ... data to create a DockerHost
   *   }
   * })
   * 
   */
  create<T extends DockerHostCreateArgs>(args: Prisma.SelectSubset<T, DockerHostCreateArgs<ExtArgs>>): Prisma.Prisma__DockerHostClient<runtime.Types.Result.GetResult<Prisma.$DockerHostPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DockerHosts.
   * @param {DockerHostCreateManyArgs} args - Arguments to create many DockerHosts.
   * @example
   * // Create many DockerHosts
   * const dockerHost = await prisma.dockerHost.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DockerHostCreateManyArgs>(args?: Prisma.SelectSubset<T, DockerHostCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DockerHosts and returns the data saved in the database.
   * @param {DockerHostCreateManyAndReturnArgs} args - Arguments to create many DockerHosts.
   * @example
   * // Create many DockerHosts
   * const dockerHost = await prisma.dockerHost.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DockerHosts and only return the `id`
   * const dockerHostWithIdOnly = await prisma.dockerHost.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DockerHostCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DockerHostCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DockerHostPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DockerHost.
   * @param {DockerHostDeleteArgs} args - Arguments to delete one DockerHost.
   * @example
   * // Delete one DockerHost
   * const DockerHost = await prisma.dockerHost.delete({
   *   where: {
   *     // ... filter to delete one DockerHost
   *   }
   * })
   * 
   */
  delete<T extends DockerHostDeleteArgs>(args: Prisma.SelectSubset<T, DockerHostDeleteArgs<ExtArgs>>): Prisma.Prisma__DockerHostClient<runtime.Types.Result.GetResult<Prisma.$DockerHostPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DockerHost.
   * @param {DockerHostUpdateArgs} args - Arguments to update one DockerHost.
   * @example
   * // Update one DockerHost
   * const dockerHost = await prisma.dockerHost.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DockerHostUpdateArgs>(args: Prisma.SelectSubset<T, DockerHostUpdateArgs<ExtArgs>>): Prisma.Prisma__DockerHostClient<runtime.Types.Result.GetResult<Prisma.$DockerHostPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DockerHosts.
   * @param {DockerHostDeleteManyArgs} args - Arguments to filter DockerHosts to delete.
   * @example
   * // Delete a few DockerHosts
   * const { count } = await prisma.dockerHost.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DockerHostDeleteManyArgs>(args?: Prisma.SelectSubset<T, DockerHostDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DockerHosts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DockerHostUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DockerHosts
   * const dockerHost = await prisma.dockerHost.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DockerHostUpdateManyArgs>(args: Prisma.SelectSubset<T, DockerHostUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DockerHosts and returns the data updated in the database.
   * @param {DockerHostUpdateManyAndReturnArgs} args - Arguments to update many DockerHosts.
   * @example
   * // Update many DockerHosts
   * const dockerHost = await prisma.dockerHost.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DockerHosts and only return the `id`
   * const dockerHostWithIdOnly = await prisma.dockerHost.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DockerHostUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DockerHostUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DockerHostPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DockerHost.
   * @param {DockerHostUpsertArgs} args - Arguments to update or create a DockerHost.
   * @example
   * // Update or create a DockerHost
   * const dockerHost = await prisma.dockerHost.upsert({
   *   create: {
   *     // ... data to create a DockerHost
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DockerHost we want to update
   *   }
   * })
   */
  upsert<T extends DockerHostUpsertArgs>(args: Prisma.SelectSubset<T, DockerHostUpsertArgs<ExtArgs>>): Prisma.Prisma__DockerHostClient<runtime.Types.Result.GetResult<Prisma.$DockerHostPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DockerHosts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DockerHostCountArgs} args - Arguments to filter DockerHosts to count.
   * @example
   * // Count the number of DockerHosts
   * const count = await prisma.dockerHost.count({
   *   where: {
   *     // ... the filter for the DockerHosts we want to count
   *   }
   * })
  **/
  count<T extends DockerHostCountArgs>(
    args?: Prisma.Subset<T, DockerHostCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DockerHostCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DockerHost.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DockerHostAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DockerHostAggregateArgs>(args: Prisma.Subset<T, DockerHostAggregateArgs>): Prisma.PrismaPromise<GetDockerHostAggregateType<T>>

  /**
   * Group by DockerHost.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DockerHostGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DockerHostGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DockerHostGroupByArgs['orderBy'] }
      : { orderBy?: DockerHostGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DockerHostGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDockerHostGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DockerHost model
 */
readonly fields: DockerHostFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DockerHost.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DockerHostClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DockerHost model
 */
export interface DockerHostFieldRefs {
  readonly id: Prisma.FieldRef<"DockerHost", 'Int'>
  readonly uuid: Prisma.FieldRef<"DockerHost", 'String'>
  readonly name: Prisma.FieldRef<"DockerHost", 'String'>
  readonly url: Prisma.FieldRef<"DockerHost", 'String'>
  readonly authKey: Prisma.FieldRef<"DockerHost", 'String'>
  readonly isActive: Prisma.FieldRef<"DockerHost", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"DockerHost", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"DockerHost", 'DateTime'>
  readonly userId: Prisma.FieldRef<"DockerHost", 'Int'>
}
    

// Custom InputTypes
/**
 * DockerHost findUnique
 */
export type DockerHostFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DockerHost
   */
  select?: Prisma.DockerHostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DockerHost
   */
  omit?: Prisma.DockerHostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DockerHostInclude<ExtArgs> | null
  /**
   * Filter, which DockerHost to fetch.
   */
  where: Prisma.DockerHostWhereUniqueInput
}

/**
 * DockerHost findUniqueOrThrow
 */
export type DockerHostFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DockerHost
   */
  select?: Prisma.DockerHostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DockerHost
   */
  omit?: Prisma.DockerHostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DockerHostInclude<ExtArgs> | null
  /**
   * Filter, which DockerHost to fetch.
   */
  where: Prisma.DockerHostWhereUniqueInput
}

/**
 * DockerHost findFirst
 */
export type DockerHostFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DockerHost
   */
  select?: Prisma.DockerHostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DockerHost
   */
  omit?: Prisma.DockerHostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DockerHostInclude<ExtArgs> | null
  /**
   * Filter, which DockerHost to fetch.
   */
  where?: Prisma.DockerHostWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DockerHosts to fetch.
   */
  orderBy?: Prisma.DockerHostOrderByWithRelationInput | Prisma.DockerHostOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DockerHosts.
   */
  cursor?: Prisma.DockerHostWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DockerHosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DockerHosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DockerHosts.
   */
  distinct?: Prisma.DockerHostScalarFieldEnum | Prisma.DockerHostScalarFieldEnum[]
}

/**
 * DockerHost findFirstOrThrow
 */
export type DockerHostFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DockerHost
   */
  select?: Prisma.DockerHostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DockerHost
   */
  omit?: Prisma.DockerHostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DockerHostInclude<ExtArgs> | null
  /**
   * Filter, which DockerHost to fetch.
   */
  where?: Prisma.DockerHostWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DockerHosts to fetch.
   */
  orderBy?: Prisma.DockerHostOrderByWithRelationInput | Prisma.DockerHostOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DockerHosts.
   */
  cursor?: Prisma.DockerHostWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DockerHosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DockerHosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DockerHosts.
   */
  distinct?: Prisma.DockerHostScalarFieldEnum | Prisma.DockerHostScalarFieldEnum[]
}

/**
 * DockerHost findMany
 */
export type DockerHostFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DockerHost
   */
  select?: Prisma.DockerHostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DockerHost
   */
  omit?: Prisma.DockerHostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DockerHostInclude<ExtArgs> | null
  /**
   * Filter, which DockerHosts to fetch.
   */
  where?: Prisma.DockerHostWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DockerHosts to fetch.
   */
  orderBy?: Prisma.DockerHostOrderByWithRelationInput | Prisma.DockerHostOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DockerHosts.
   */
  cursor?: Prisma.DockerHostWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DockerHosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DockerHosts.
   */
  skip?: number
  distinct?: Prisma.DockerHostScalarFieldEnum | Prisma.DockerHostScalarFieldEnum[]
}

/**
 * DockerHost create
 */
export type DockerHostCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DockerHost
   */
  select?: Prisma.DockerHostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DockerHost
   */
  omit?: Prisma.DockerHostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DockerHostInclude<ExtArgs> | null
  /**
   * The data needed to create a DockerHost.
   */
  data: Prisma.XOR<Prisma.DockerHostCreateInput, Prisma.DockerHostUncheckedCreateInput>
}

/**
 * DockerHost createMany
 */
export type DockerHostCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DockerHosts.
   */
  data: Prisma.DockerHostCreateManyInput | Prisma.DockerHostCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DockerHost createManyAndReturn
 */
export type DockerHostCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DockerHost
   */
  select?: Prisma.DockerHostSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DockerHost
   */
  omit?: Prisma.DockerHostOmit<ExtArgs> | null
  /**
   * The data used to create many DockerHosts.
   */
  data: Prisma.DockerHostCreateManyInput | Prisma.DockerHostCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DockerHostIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DockerHost update
 */
export type DockerHostUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DockerHost
   */
  select?: Prisma.DockerHostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DockerHost
   */
  omit?: Prisma.DockerHostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DockerHostInclude<ExtArgs> | null
  /**
   * The data needed to update a DockerHost.
   */
  data: Prisma.XOR<Prisma.DockerHostUpdateInput, Prisma.DockerHostUncheckedUpdateInput>
  /**
   * Choose, which DockerHost to update.
   */
  where: Prisma.DockerHostWhereUniqueInput
}

/**
 * DockerHost updateMany
 */
export type DockerHostUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DockerHosts.
   */
  data: Prisma.XOR<Prisma.DockerHostUpdateManyMutationInput, Prisma.DockerHostUncheckedUpdateManyInput>
  /**
   * Filter which DockerHosts to update
   */
  where?: Prisma.DockerHostWhereInput
  /**
   * Limit how many DockerHosts to update.
   */
  limit?: number
}

/**
 * DockerHost updateManyAndReturn
 */
export type DockerHostUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DockerHost
   */
  select?: Prisma.DockerHostSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DockerHost
   */
  omit?: Prisma.DockerHostOmit<ExtArgs> | null
  /**
   * The data used to update DockerHosts.
   */
  data: Prisma.XOR<Prisma.DockerHostUpdateManyMutationInput, Prisma.DockerHostUncheckedUpdateManyInput>
  /**
   * Filter which DockerHosts to update
   */
  where?: Prisma.DockerHostWhereInput
  /**
   * Limit how many DockerHosts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DockerHostIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DockerHost upsert
 */
export type DockerHostUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DockerHost
   */
  select?: Prisma.DockerHostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DockerHost
   */
  omit?: Prisma.DockerHostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DockerHostInclude<ExtArgs> | null
  /**
   * The filter to search for the DockerHost to update in case it exists.
   */
  where: Prisma.DockerHostWhereUniqueInput
  /**
   * In case the DockerHost found by the `where` argument doesn't exist, create a new DockerHost with this data.
   */
  create: Prisma.XOR<Prisma.DockerHostCreateInput, Prisma.DockerHostUncheckedCreateInput>
  /**
   * In case the DockerHost was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DockerHostUpdateInput, Prisma.DockerHostUncheckedUpdateInput>
}

/**
 * DockerHost delete
 */
export type DockerHostDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DockerHost
   */
  select?: Prisma.DockerHostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DockerHost
   */
  omit?: Prisma.DockerHostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DockerHostInclude<ExtArgs> | null
  /**
   * Filter which DockerHost to delete.
   */
  where: Prisma.DockerHostWhereUniqueInput
}

/**
 * DockerHost deleteMany
 */
export type DockerHostDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DockerHosts to delete
   */
  where?: Prisma.DockerHostWhereInput
  /**
   * Limit how many DockerHosts to delete.
   */
  limit?: number
}

/**
 * DockerHost without action
 */
export type DockerHostDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DockerHost
   */
  select?: Prisma.DockerHostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DockerHost
   */
  omit?: Prisma.DockerHostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DockerHostInclude<ExtArgs> | null
}
